# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Granada 2018"
email: "contacto@gdggranada.com"
description: "GDG DevFest Granada 2018. El punto de encuentro con tu comunidad local"
baseurl: ""
url: "https://devfest.gdggranada.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "GDG Granada"
organizerAlternateName: "Google Developer Group Granada"
organizerDescription: "GDG Granada es una entidad sin ánimo de lucro creada con el objetivo de mejorar la comunidad de entusiastas tecnológicos y aumentar el conocimiento y las relaciones entre las personas que se dedican a esta área."
organizerEmail: "contacto@gdgranada.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdggranada.com"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, granada"
twitterAccount: "@GDGGranada"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://t.co/2fSHWKyjkn"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Ponentes"}
 - {permalink: "/team/", text: "Organizadores"}
rightNavigationButtons:
 - {link: "https://www.meetup.com/es-ES/granadagdg/events/253173823/", text: "Registro"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest Granada"
eventDate: "16 de noviembre"
typeoutTextValues: '"", " 2018", " Season", " Granada"'
typeoutFallback: " Season"
heroButtons:
 - {link: "https://www.meetup.com/es-ES/granadagdg/events/253173823/", text: "Registro"}

# About Block
aboutTitle: "Sobre GDG DevFest Granada"
aboutBlock:
 - {title: "Ponentes", image: "conference.jpg", text: "Ponentes de primer nivel venidos desde toda España" }
 - {title: "Tecnología", image: "hackathon.jpg", text: "Ven y aprende con nosotros sobre las tecnologías más novedosas" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "+", info: "asistentes", detail: "y tú tienes que ser uno de ellos"}
 - {count: "8", specialCharacter: "+", info: "hours", detail: "horas de tecnología"}
 - {count: "8", specialCharacter: "+", info: "ponentes", detail: "de primer nivel"}
 - {count: "2", specialCharacter: "", info: "tracks paralelos", detail: "poara que tengas dóndde elegir"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 8
rockstarSpeakersTitle: "Nuestros ponentes"
rockstarSpeakersButtonText: "Saber más"

# Location Block
locationBlockTitle: "Localización"
eventLocationName: ""
eventLocationLink: ""
eventStreetAddress: "Calle Periodista Daniel Saucedo Aranda, s/n"
eventAddressLocality: "Granada"
eventAddressLocalityRegion: "Granada"
eventPostalCode: "18014"
eventAddressCountry: "España"
eventStartTime: "2018-11-16T09:30"
eventDoorTime: "09:15"
eventEndTime: "2018-11-16T20:00"
eventPlaceCoordinates: "37.1970867, -3.624686"
mapCenterCoordinates: "37.1970867, -3.624686"
mapMobileCenterCoordinates: "37.1970867, -3.624686"

# Venue Block
venueBlockTitle: "¿Dónde vamos a celebrar el evento?"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Escuela Técnica Superior de Ingenierías Informática y Telecomunicación de la UGR"
venueFeatures: ["Calle Periodista Daniel Saucedo Aranda, s/n, 18014 Granada", "http://etsiit.ugr.es/"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "¿Quieres seguir el evento por redes sociales?"
twitterHashTag: "devfestgrx"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Tickets"
ticketsInfo: "El registro es obligatorio si quieres participar en todas nuestras actividades, tener posibilidad de participar en los concursos realizados durante el evento y... ¡mucho más!"
ticketsOffers:
 -
  name: "Registro"
  price: "0"
  priceCurrency: "EUROS"
  ticketsNumber: "200"
  ribbon: ""
  buyButtonLink: "https://www.meetup.com/es-ES/granadagdg/events/253173823/"
  buyButtonText: "Registro"
  ticketContentList: [""]
  validFrom: "2018-08-25T10:00"
  validThrough: "2018-11-1T00:00"

# Footer
socialLinks:
 - {link: "https://twitter.com/GDGGranada", icon: "twitter"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdggranada.com", text: "GDG Granada"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacto"
  links:
   - {link: "mailto:contacto@gdggranada.com", text: "contacto@gdggranada.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de conducta"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Sobre nosotros"
aboutUs: "Los Google Developer Groups (GDGs) son entidades sin ánimo de lucro creadas con el objetivo de mejorar la comunidad de entusiastas tecnológicos y aumentar el conocimiento y las relaciones entre las personas que se dedican a esta área. GDG Granada es la rama local de esta comunidad."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
